fix(github): renames issue template file to align with pattern
error: GitHub was not registering the template

cause: The current standard does not accept uppercase letters

solution: Rename the file to lowercase letters